name: Test

on:
  workflow_run:
      workflows: ["Build"]
      types:
        - completed

env:
  BUILD_TYPE: Release
  BUILD_TESTS: ON
  CODE_COVERAGE: ON

jobs:
  test:
    if: $ {{github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
          name: build-artifact
          path: ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Coverage
      working-directory: ${{github.workspace}}/build
      run: gcovr -r ${{github.workspace}}/src .
